# Generated by Django 3.0 on 2022-10-28 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=30, verbose_name='Primer Nombre')),
                ('segundo_nombre', models.CharField(blank=True, max_length=30, null=True, verbose_name='Segundo Nombre')),
                ('primer_apellido', models.CharField(max_length=30, verbose_name='Primer Apellido')),
                ('segundo_apellido', models.CharField(blank=True, max_length=30, null=True, verbose_name='Segundo Apellido')),
                ('apellido_esposo', models.CharField(blank=True, max_length=30, null=True, verbose_name='Apellido Esposo')),
                ('valor_documento_identificacion', models.CharField(max_length=20, unique=True, verbose_name='Cedula de Identidad')),
                ('complemento', models.CharField(blank=True, max_length=20, null=True, verbose_name='Complemento')),
                ('extension', models.CharField(choices=[('CH', 'CH'), ('LP', 'LP'), ('SC', 'SC'), ('CB', 'CB'), ('OR', 'OR'), ('TA', 'TA'), ('PO', 'PO'), ('BE', 'BE'), ('PA', 'PA'), ('SE', 'Sin Extencion')], help_text='Extension de documento de identidad', max_length=2, verbose_name='Extension de documento de identidad')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Eliminacion')),
                ('sucursal_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursal_creacion_sucursal', to='empresa.Sucursal', verbose_name='Sucursal_Creacion')),
                ('usuario_actualizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_actualizacion_user', to=settings.AUTH_USER_MODEL, verbose_name='Usuario_Actualizacion')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'adm_tbl_persona',
                'permissions': (('listar_todo_personas', 'Puede listar todas las personas'),),
            },
        ),
    ]
