# Generated by Django 3.0 on 2022-11-16 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_caja', models.CharField(max_length=100, verbose_name='Descripcion')),
                ('saldo_minimo_mn', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Saldo Minimo MN')),
                ('saldo_maximo_mn', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Saldo Maximo MN')),
                ('saldo_minimo_me', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Saldo Minimo ME')),
                ('saldo_maximo_me', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Saldo Maximo ME')),
                ('saldo_minimo_mr', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Saldo Minimo MR')),
                ('saldo_maximo_mr', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Saldo Maximo MR')),
                ('ultima_apertura', models.DateTimeField(blank=True, null=True, verbose_name='Ultima Apertura')),
                ('ultimo_cuadre', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='Ultimo Cuadre')),
                ('habilitada', models.CharField(choices=[('V', 'Verdadero'), ('F', 'Falso')], default='V', max_length=1, verbose_name='Habilitada')),
                ('saldo_mn', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Saldo MN')),
                ('saldo_me', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Saldo ME')),
                ('saldo_mr', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Saldo MR')),
                ('estado_caja', models.CharField(choices=[('V', 'Vigente'), ('B', 'Bloqueado')], default='V', max_length=1, verbose_name='Estado Caja')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True, null=True)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Eliminacion')),
                ('codigo_oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigo_oficina_caja', to='empresa.Sucursal', verbose_name='Codigo Oficina')),
                ('codigo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigo_usuario_caja', to=settings.AUTH_USER_MODEL, verbose_name='Codigo_Usuario')),
                ('sucursal_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursal_creacion_caja', to='empresa.Sucursal', verbose_name='Sucursal Creacion')),
                ('usuario_actualizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_actualizacion_caja', to=settings.AUTH_USER_MODEL, verbose_name='Usuario actualizacion')),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'db_table': 'caj_cajas',
                'unique_together': {('descripcion_caja',)},
            },
        ),
        migrations.CreateModel(
            name='CorteMoneda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneda_id', models.PositiveSmallIntegerField(verbose_name='Moneda')),
                ('descripcion_corte_moneda', models.CharField(max_length=100, verbose_name='Descripcion corete moneda')),
                ('valor_corte_moneda', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor Corte moneda')),
                ('creado_en', models.DateTimeField()),
                ('actualizado_en', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Actualizacion')),
                ('eliminado_en', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Eliminacion')),
                ('sucursal_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursal_creacion_corte_moneda', to='empresa.Sucursal', verbose_name='Sucursal Creacion')),
                ('usuario_actualizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_actualizacion_corte_moneda', to=settings.AUTH_USER_MODEL, verbose_name='Usuario actualizacion')),
            ],
            options={
                'verbose_name': 'Corte Moneda',
                'verbose_name_plural': 'Cortes Monedas',
                'db_table': 'caj_cortes_monedas',
            },
        ),
        migrations.CreateModel(
            name='TransaccionInventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_transaccion', models.DateTimeField(verbose_name='Fecha Transaccion')),
                ('producto_financiero_id', models.PositiveSmallIntegerField(choices=[(51, 'Electrodomesticos'), (52, 'Viveres'), (53, 'Temporada'), (54, 'Articulos del Hogar'), (55, 'Otros')], verbose_name='Codigo Producto Financiero')),
                ('detalle', models.TextField(verbose_name='Detalle')),
                ('fondo', models.CharField(choices=[('A', 'Fondo A'), ('B', 'Fondo B')], max_length=1, verbose_name='Fondo')),
                ('monto_ingreso', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Monto Ingreso')),
                ('monto_salida', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Monto Ingreso')),
                ('creado_en', models.DateTimeField()),
                ('actualizado_en', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Actualizacion')),
                ('eliminado_en', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Eliminacion')),
                ('caja_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigo_caja_transaccioninventario', to='cajas.Caja', verbose_name='Codigo Caja')),
                ('sucursal_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursal_creacion_transaccioninventario', to='empresa.Sucursal', verbose_name='Sucursal Creacion')),
                ('usuario_actualizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_actualizacion_transaccioninventario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario actualizacion')),
            ],
            options={
                'verbose_name': 'Transaccion Inventario',
                'verbose_name_plural': 'Transacciones Inventarios',
                'db_table': 'caj_transaccion_inventario',
            },
        ),
        migrations.CreateModel(
            name='EncabezadoArqueo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_arqueo', models.DateTimeField(verbose_name='Fecha arqueo')),
                ('total_arqueo_mn', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Arqueo MN')),
                ('total_arqueo_me', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Arqueo ME')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('arqueo_definitivo', models.BooleanField(default=True, verbose_name='¿Es arqueo definitivo?')),
                ('creado_en', models.DateTimeField()),
                ('actualizado_en', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Actualizacion')),
                ('eliminado_en', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Eliminacion')),
                ('caja_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigo_caja_encabezadoarqueo', to='cajas.Caja', verbose_name='Codigo Caja')),
                ('sucursal_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursal_creacion_encabezadoarqueo', to='empresa.Sucursal', verbose_name='Sucursal Creacion')),
                ('usuario_actualizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_actualizacion_encabezado_arqueo', to=settings.AUTH_USER_MODEL, verbose_name='Usuario actualizacion')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigo_usuario_encabezadoarqueo', to=settings.AUTH_USER_MODEL, verbose_name='Codigo Usiario')),
            ],
            options={
                'verbose_name': 'Encabezado Arqueo',
                'verbose_name_plural': 'Encabezados Arqueos',
                'db_table': 'caj_arqueo',
            },
        ),
        migrations.CreateModel(
            name='DetalleArqueo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneda_id', models.PositiveSmallIntegerField(verbose_name='Moneda')),
                ('cantidad_corte_moneda', models.IntegerField(help_text='Cantidad corte moneda', verbose_name='Cantidad Corte Moneda')),
                ('valor_corte_moneda', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Corte moneda')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True, null=True)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Eliminacion')),
                ('arqueo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_arqueo_encabezado', to='cajas.EncabezadoArqueo', verbose_name='Arqueo Id')),
                ('corte_moneda_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corte_moneda', to='cajas.CorteMoneda', verbose_name='Corte Moneda')),
                ('sucursal_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursal_creacion_detalle_arqueo', to='empresa.Sucursal', verbose_name='Sucursal Creacion')),
                ('usuario_actualizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_actualizacion_detalle_arqueo', to=settings.AUTH_USER_MODEL, verbose_name='Usuario actualizacion')),
            ],
            options={
                'verbose_name': 'Detalle Arqueo',
                'verbose_name_plural': 'Detalles Arqueos',
                'db_table': 'caj_detalle_arqueo',
            },
        ),
        migrations.CreateModel(
            name='CuentasPorCobrar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateTimeField(verbose_name='Fecha Entrega')),
                ('monto_entregado', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Monto po cobrar')),
                ('monto_devuelto', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Monto a Cuenta')),
                ('monto_saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='monto Saldo')),
                ('fecha_ultimo_pago', models.DateTimeField(blank=True, null=True, verbose_name='Ultima Fecha Pago')),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('C', 'Cancelado')], default='P', max_length=1, verbose_name='Estado')),
                ('creado_en', models.DateTimeField(verbose_name='Fecha creacion')),
                ('actualizado_en', models.DateTimeField(blank=True, null=True, verbose_name='Fecha actualizacion')),
                ('eliminado_en', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Eliminacion')),
                ('caja_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigo_caja_cuentasporcobrar', to='cajas.Caja', verbose_name='Codigo Caja')),
                ('funcionario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigo_funcionario_cuentasporcobrar', to=settings.AUTH_USER_MODEL, verbose_name='Codigo Funcionario')),
                ('sucursal_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursal_creacion_cuentasporcobrar', to='empresa.Sucursal', verbose_name='Sucursal Creacion')),
                ('usuario_actualizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_actualizacion_cuentasporcobrar', to=settings.AUTH_USER_MODEL, verbose_name='Usuario actualizacion')),
            ],
            options={
                'verbose_name': 'Cuenta por Cobrar',
                'verbose_name_plural': 'Cuentas por Cobrar',
                'db_table': 'caj_cuentas_por_cobrar',
            },
        ),
    ]
