version: '3.4'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
#    image: ${REPOSITORY_TESTING_URI}
    volumes:
      - .:/app
    environment:
      MYSQL_DATABASE: "simicrofin_jdgp"
      MYSQL_USER: "evillanueva"
      MYSQL_PASSWORD: "evillanueva"
      MYSQL_ROOT_PASSWORD: "docker-root"

  db:
    environment:
      MYSQL_DATABASE: "simicrofin_jdgp"
      MYSQL_USER: "evillanueva"
      MYSQL_PASSWORD: "evillanueva"
      MYSQL_ROOT_PASSWORD: "docker-root"

