# Generated by Django 3.0 on 2022-10-04 20:54

import apps.contrib.utils.strings
from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=apps.contrib.utils.strings.get_uuid5, unique=True, verbose_name='Slug')),
                ('codigo', models.CharField(max_length=5, verbose_name='codigo')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='direccion')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=apps.contrib.utils.strings.get_uuid5, unique=True, verbose_name='Slug')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('direccion', models.TextField(verbose_name='direccion')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefono/Celular')),
                ('punto_gps', location_field.models.plain.PlainLocationField(blank=True, default='-16.510659, -68.141776', max_length=63, null=True, verbose_name='Punto GPS')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='sucursales/%Y%m%d/', verbose_name='Fotografia')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'db_table': 'sucursal',
            },
        ),
    ]
